### PR TITLE
Fix world map gets modified on the default map 

### LINKED ISSUE #60: World map gets modified on the default map
Causes all station name to disappear

### PR DESCRIPTION
**Pull request by t0stiman**
fixes #60

### CODE REVIEW

File: Mapify/Utils/Extensions.cs [hunk 1]
```diff
@@ -17,6 +17,8 @@ namespace Mapify.Utils
 {
     public static class Extensions
     {
+        private const string jObjectName = "mapify";
```
Comment (Insprill) [inline Mapify/Utils/Extensions.cs:20]: const's should use SCREAKING_SNAKE_CASE. It could be named something like `SAVE_KEY_NAME`

File: Mapify/SceneInitializers/GameContent/WorldMapSetup.cs [hunk 2]
```diff
@@ -80,36 +80,44 @@ public static void UpdateMap(Transform transform)
                 modifiedMaterial = true;
             }
 
-            Transform names = transform.FindChildByName("Names");
-            if (names == null)
+            ShowNamesOnMap(mapTransform, isStationOfficeMap);
+        }
+
+        private static void ShowNamesOnMap(Transform mapTransform, bool isStationOfficeMap)
```
Comment (Insprill) [inline Mapify/SceneInitializers/GameContent/WorldMapSetup.cs:86]: What's the purpose of the isStationOfficeMap parameter? Please don't include seemingly unrelated changes to the PR without at least explaining the purpose in the description. It would save me time trying to figure out what all you've done and why.

**Review by Insprill — CHANGES_REQUESTED** [review]

File: Mapify/SceneInitializers/GameContent/WorldMapSetup.cs (hunk 2 above)
Comment (t0stiman) [reply Mapify/SceneInitializers/GameContent/WorldMapSetup.cs:86]: My bad. TBH, I don't really remember why I did that but it seems incorrect. Removed.

File: Mapify/Utils/Extensions.cs (hunk 1 above)
Comment (t0stiman) [reply Mapify/Utils/Extensions.cs:20]: changed

**Review by Insprill — APPROVED** [review]
LGTM. Thank you!
