### PR TITLE
Fix job booklets spawn under station

### LINKED ISSUE #28: Job booklets don't spawn
the cars for the jobs spawn, but the booklets don't, I've tried moving the stations up and there's no booklets under them either, tried using a box collider and it didn't spawn them either.

I am using the prefab station, and they don't come back in the lost and found either.

### PR DESCRIPTION
**Pull request by t0stiman**
Fixes #28

afbeelding

### CODE REVIEW

File: Mapify/SceneInitializers/GameContent/StationSetup.cs [hunk 1]
```diff
@@ -52,13 +52,16 @@ public override void Run()
...
-            jobBookletSpawnSurface.xSize = size.x;
-            jobBookletSpawnSurface.xSize = size.z;
+
+            if (jobBookletSpawnSurface == null)
+            {
+                GameObject jobBookletSpawnSurfaceObject = station.gameObject.NewChildWithPosition("JobSpawnerAnchor", station.transform.TransformPoint(station.bookletSpawnArea.center));
+                jobBookletSpawnSurface = jobBookletSpawnSurfaceObject.AddComponent<PointOnPlane>();
+                Vector3 size = station.bookletSpawnArea.size;
+                jobBookletSpawnSurface.xSize = size.x;
+                jobBookletSpawnSurface.xSize = size.z;
```
Comment (Insprill) [inline Mapify/SceneInitializers/GameContent/StationSetup.cs:62]: These are both setting xSize, not sure how I ever missed that but now would be a good time to fix it

**Review by Insprill — CHANGES_REQUESTED** [review]

File: Mapify/SceneInitializers/GameContent/StationSetup.cs (hunk 1 above)
Comment (t0stiman) [reply Mapify/SceneInitializers/GameContent/StationSetup.cs]: done

**Review by Insprill — APPROVED** [review]
LGTM. Thank you!
